In [193]:
from sklearn import feature_extraction
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer

In [6]:
from scipy import sparse
from numpy import *

In [5]:
help(sparse)

Help on package scipy.sparse in scipy:

NAME
    scipy.sparse

FILE
    d:\anaconda2\lib\site-packages\scipy\sparse\__init__.py

DESCRIPTION
    Sparse matrices (:mod:`scipy.sparse`)
    
    .. currentmodule:: scipy.sparse
    
    SciPy 2-D sparse matrix package for numeric data.
    
    Contents
    
    Sparse matrix classes
    ---------------------
    
    .. autosummary::
       :toctree: generated/
    
       bsr_matrix - Block Sparse Row matrix
       coo_matrix - A sparse matrix in COOrdinate format
       csc_matrix - Compressed Sparse Column matrix
       csr_matrix - Compressed Sparse Row matrix
       dia_matrix - Sparse matrix with DIAgonal storage
       dok_matrix - Dictionary Of Keys based sparse matrix
       lil_matrix - Row-based linked list sparse matrix
       spmatrix - Sparse matrix base class
    
    Functions
    ---------
    
    Building sparse matrices:
    
    .. autosummary::
       :toctree: generated/
    
       eye - Sparse MxN matrix whose k-t

In [169]:
tfidftrans = TfidfTransformer()

In [170]:
rows = random.randint(0, 10, (1, 30))
cols = random.randint(0, 10, (1, 30))
data = random.randint(0, 12, (1, 30))
c = sparse.coo_matrix((data[0], (rows[0], cols[0])), shape=(10, 10))

In [171]:
c.toarray()

array([[ 0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0, 11,  0,  6,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  7,  0, 11, 14,  0],
       [ 0,  4, 11,  8,  0,  0,  0,  5,  0,  7],
       [ 6,  7,  0,  0,  0,  0,  0,  4,  0,  4],
       [11,  0,  0,  8,  0,  0,  0,  9,  3,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0,  0,  0,  0,  0]])

In [172]:
tfidf = tfidftrans.fit_transform(c)

In [173]:
tfidf.toarray()

array([[ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.15709844,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.98758295,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.50203506,  0.        ,  0.41413396,
         0.        ,  0.75924559,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.3877947 ,  0.        ,
         0.45614785,  0.        ,  0.42565302,  0.67850122,  0.        ],
       [ 0.        ,  0.29085853,  0.62215795,  0.45247851,  0.        ,
         0.        ,  0.        ,  0.25396955,  0.        ,  0.50900242],
       [ 0.47986503,  0.71974677,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.28729728

In [206]:
ca = c.toarray()

In [207]:

ca = array(ca, dtype=float)
ca

array([[  0.,   0.,   7.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  10.,   0.],
       [  1.,   0.,   0.,   0.,   0.,   0.,   0.,   7.,   0.,   0.],
       [  0.,   0.,  11.,   0.,   6.,   0.,  11.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   9.,   0.,   7.,   0.,  11.,  14.,   0.],
       [  0.,   4.,  11.,   8.,   0.,   0.,   0.,   5.,   0.,   7.],
       [  6.,   7.,   0.,   0.,   0.,   0.,   0.,   4.,   0.,   4.],
       [ 11.,   0.,   0.,   8.,   0.,   0.,   0.,   9.,   3.,   0.],
       [  5.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   5.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [208]:
ca.sum(axis=0)

array([ 23.,  11.,  29.,  30.,   6.,   7.,  11.,  36.,  27.,  11.])

In [209]:
ca.sum(axis=1)

array([  7.,  10.,   8.,  28.,  41.,  35.,  21.,  31.,   5.,   5.])

In [210]:
d = ca.sum(axis=1)

In [211]:
tf = ca / ca.sum(axis=1).reshape((10, 1))

In [212]:
tf

array([[ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.125     ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.875     ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.39285714,  0.        ,  0.21428571,
         0.        ,  0.39285714,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.2195122 ,  0.        ,
         0.17073171,  0.        ,  0.26829268,  0.34146341,  0.        ],
       [ 0.        ,  0.11428571,  0.31428571,  0.22857143,  0.        ,
         0.        ,  0.        ,  0.14285714,  0.        ,  0.2       ],
       [ 0.28571429,  0.33333333,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.19047619

In [213]:
caidf = ca.copy()

In [214]:
caidf[caidf!=0] = 1.0

In [215]:
caidf

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.],
       [ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [231]:
caidf.sum(axis=0)

array([ 4.,  2.,  3.,  4.,  1.,  1.,  1.,  5.,  3.,  2.])

In [232]:
idf = 11 / (caidf.sum(axis=0) + 1)

In [233]:
idf

array([ 2.2       ,  3.66666667,  2.75      ,  2.2       ,  5.5       ,
        5.5       ,  5.5       ,  1.83333333,  2.75      ,  3.66666667])

In [234]:
newidf = log(idf) + 1

In [235]:
newidf

array([ 1.78845736,  2.29928298,  2.01160091,  1.78845736,  2.70474809,
        2.70474809,  2.70474809,  1.6061358 ,  2.01160091,  2.29928298])

In [236]:
newidf1 = newidf * tf
newidf1

array([[ 0.        ,  0.        ,  2.01160091,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  2.01160091,  0.        ],
       [ 0.22355717,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.40536883,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.79027179,  0.        ,  0.57958888,
         0.        ,  1.06257961,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.3925882 ,  0.        ,
         0.46178626,  0.        ,  0.43091448,  0.68688812,  0.        ],
       [ 0.        ,  0.2627752 ,  0.63221743,  0.40879025,  0.        ,
         0.        ,  0.        ,  0.22944797,  0.        ,  0.4598566 ],
       [ 0.51098782,  0.76642766,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.30593063

In [237]:
newidf1.sum(axis=1)

array([ 2.01160091,  2.01160091,  1.628926  ,  2.43244027,  1.97217706,
        1.99308745,  2.02130477,  1.75711983,  1.78845736,  1.78845736])

In [238]:
newidf1 / newidf1.sum(axis=1).reshape((10, 1))

array([[ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.13724207,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.86275793,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.32488847,  0.        ,  0.23827466,
         0.        ,  0.43683688,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.19906336,  0.        ,
         0.23415051,  0.        ,  0.21849685,  0.34828927,  0.        ],
       [ 0.        ,  0.13184329,  0.31720506,  0.20510402,  0.        ,
         0.        ,  0.        ,  0.11512188,  0.        ,  0.23072575],
       [ 0.25280098,  0.37917472,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.15135304

In [239]:
c.toarray()

array([[ 0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0, 11,  0,  6,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  7,  0, 11, 14,  0],
       [ 0,  4, 11,  8,  0,  0,  0,  5,  0,  7],
       [ 6,  7,  0,  0,  0,  0,  0,  4,  0,  4],
       [11,  0,  0,  8,  0,  0,  0,  9,  3,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0,  0,  0,  0,  0]])

In [240]:
tfidf = tfidftrans.fit_transform(c)

In [241]:
tfidf.toarray()

array([[ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.15709844,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.98758295,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.50203506,  0.        ,  0.41413396,
         0.        ,  0.75924559,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.3877947 ,  0.        ,
         0.45614785,  0.        ,  0.42565302,  0.67850122,  0.        ],
       [ 0.        ,  0.29085853,  0.62215795,  0.45247851,  0.        ,
         0.        ,  0.        ,  0.25396955,  0.        ,  0.50900242],
       [ 0.47986503,  0.71974677,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.28729728

In [196]:
c.toarray()

array([[ 0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0, 11,  0,  6,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  7,  0, 11, 14,  0],
       [ 0,  4, 11,  8,  0,  0,  0,  5,  0,  7],
       [ 6,  7,  0,  0,  0,  0,  0,  4,  0,  4],
       [11,  0,  0,  8,  0,  0,  0,  9,  3,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0,  0,  0,  0,  0]])

In [199]:
idftransfor = TfidfVectorizer(min_df=1)

In [204]:
c.toarray()

array([[ 0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  7,  0,  0],
       [ 0,  0, 11,  0,  6,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  9,  0,  7,  0, 11, 14,  0],
       [ 0,  4, 11,  8,  0,  0,  0,  5,  0,  7],
       [ 6,  7,  0,  0,  0,  0,  0,  4,  0,  4],
       [11,  0,  0,  8,  0,  0,  0,  9,  3,  0],
       [ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  5,  0,  0,  0,  0,  0,  0]])

In [205]:
idf = idftransfor.fit_transform(c.toarray())

AttributeError: 'list' object has no attribute 'lower'